// SETTINGS
export const SET_TIME_MULTIPLIER = "SET_TIME_MULTIPLIER";
export const SET_QUANTITY_MULTIPLIER = "SET_QUANTITY_MULTIPLIER";
export const SET_RANDOM_SEED = "SET_RANDOM_SEED";
export const SET_DPR = "SET_DPR";
export const SET_ANTI_ALIAS = "SET_ANTI_ALIAS";
export const SET_DEBUG = "SET_DEBUG";
