// SETTINGS
export const SET_TIME_MULTIPLIER = "SET_TIME_MULTIPLIER";
export const SET_QUANTITY_MULTIPLIER = "SET_QUANTITY_MULTIPLIER";
export const SET_RANDOM_SEED = "SET_RANDOM_SEED";
export const SET_DPR = "SET_DPR";
export const SET_ANTI_ALIAS = "SET_ANTI_ALIAS";
export const SET_DEBUG = "SET_DEBUG";

// CHAPTERS
export const FOCUS_CHAPTER = "FOCUS_CHAPTER";
export const ADD_CHAPTER = "ADD_CHAPTER";

// PRESENTATION MODE
export const RANDOM_CYCLE = "RANDOM_CYCLE";
export const EXPLORE = "EXPLORE";
export const PRESENTATION_MODE_DEFAULT = RANDOM_CYCLE;
