export default [
  "precision highp float;",
  "",
  "uniform float time;",
  "uniform vec3 color;",
  "",
  "uniform mat4 modelViewMatrix;",
  "uniform mat4 projectionMatrix;",
  "",
  "attribute vec3 position;",
  "attribute vec3 offset;",
  "attribute vec4 orientationStart;",
  "attribute vec4 orientationEnd;",
  "",
  "varying vec3 vPosition;",
  "varying vec4 vColor;",
  "",
  "void main(){",
  "",
  "    vPosition = offset + position + vec3(time * 10., 0, 0);",
  "    vec4 orientation = normalize( mix( orientationStart, orientationEnd, time ) );",
  "    vec3 vcV = cross( orientation.xyz, vPosition );",
  "    vPosition = vcV * ( 2.0 * orientation.w ) + ( cross( orientation.xyz, vcV ) * 2.0 + vPosition );",
  "",
  "    vColor = vec4( color, time );",
  "",
  "    gl_Position = projectionMatrix * modelViewMatrix * vec4( vPosition, 1.0 );",
  "",
  "}"
];
